#!/bin/bash

# This launches iex w/ the following:
#
# 1.  The epcd environment variable set so that other computers can access this Elixir instance.
# 2.  The port range so that other computers can access this as a node.
iex --name "router@24.249.34.237" --cookie paypal_ipn_forwarder --erl "-kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9115" -S mix
