#!/bin/bash

# This launches iex w/ the following:
#
# 1.  The epcd environment variable set so that other computers can access this Elixir instance.
# 2.  The port range so that other computers can access this as a node.
echo "PAYPAL_IPN_HOST is '$PAYPAL_IPN_HOST'"
echo "PAYPAL_IPN_COOKIE is '$PAYPAL_IPN_COOKIE'"
iex --name "server@$PAYPAL_IPN_HOST" --cookie $PAYPAL_IPN_COOKIE --erl "-kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9115" -S mix
